config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :locations
  resources :bookings
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource :password, only: %i[edit update]
  namespace :identity do
    resource :email, only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset, only: %i[new edit create update]
  end
  post 'users/:user_id/masquerade', to: 'masquerades#create', as: :user_masquerade
  resource :invitation, only: %i[new create]
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create_with(user_params).find_or_initialize_by(email: params[:email])

    if @user.save
      send_invitation_instructions
      redirect_to new_invitation_path, notice: "An invitation email has been sent to #{@user.email}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.permit(:email).merge(password: SecureRandom.base58, verified: true)
    end

    def send_invitation_instructions
      UserMailer.with(user: @user).invitation_instructions.deliver_later
    end
end

app/views/invitations/new.html.erb
<p style="color: green"><%= notice %></p>

<h1>Send invitation</h1>

<%= form_with(url: invitation_path) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, required: true, autofocus: true %>
  </div>

  <div>
    <%= form.submit "Send an invitation" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back", root_path %>
</div>