config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :locations
  resources :bookings
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource :password, only: %i[edit update]
  namespace :identity do
    resource :email, only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset, only: %i[new edit create update]
  end
  post 'users/:user_id/masquerade', to: 'masquerades#create', as: :user_masquerade
  resource :invitation, only: %i[new create]
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :owner_user, class_name: 'User'
  has_one_attached :cover
  has_many :bookings

  def taken?(start_time, end_time)
    Booking.where(location_id: id)
           .where('(start_at <= ? AND end_at >= ?) OR (start_at <= ? AND end_at >= ?) OR (start_at >= ? AND end_at <= ?)',
                  start_time, start_time, end_time, end_time, start_time, end_time)
           .exists?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show edit update destroy]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show; end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit; end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy!

    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.includes('bookings').find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def location_params
    params.require(:location).permit(:name, :cover)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, class: "contents") do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cover %>
    <%= form.file_field :cover, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <div>
    <% if location.cover.attached? %>
      <% if action_name != "show" %>
        <%= link_to location do %>
          <img src="<%= url_for(location.cover) %>" class="object-cover w-full h-48" alt="">
        <% end %>
      <% else %>
        <div style="background-image: url(<%= url_for(location.cover) %>)" class=" relative bg-center bg-cover w-full h-32">

          <p class="absolute bottom-0 left-0">
            <strong class="block bg-black/50 m-2 p-2 text-white font-medium"><%= location.name %></strong>
          </p>
        </div>

      <% end %>
    <% end %>
  </div>

</div>

app/views/locations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing location</h1>

  <%= render "form", location: @location %>

  <%= link_to "Show this location", @location, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to locations", locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p
      class="
        inline-block
        px-3
        py-2
        mb-5
        font-medium
        text-green-500
        rounded-lg
        bg-green-50
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Locations</h1>
    <%= link_to "New location",
    new_location_path,
    class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="locations" class="grid min-w-full grid-cols-2 gap-8">
    <%= render @locations %>
  </div>
</div>

app/views/locations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New location</h1>

  <%= render "form", location: @location %>

  <%= link_to "Back to locations", locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locations/show.html.erb
<div class="flex flex-col gap-6 w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>
  <%= render @location %>
  <div class="flex flex-grow justify-end">
    <%= link_to t("New Booking"), new_booking_path(@location), class: "w-48 mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
  <% unless @location.bookings.empty? %>
    <h2 class="text-xl"><%= t('bookings') %></h2>
    <div class="grid w-full grid-cols-3 gap-4">
      <%= render @location.bookings %>
    </div>
  <% end %>
  <%= link_to "Edit this location", edit_location_path(@location), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this location", location_path(@location), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
  <%= link_to "Back to locations", locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>