config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :locations
  resources :bookings
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource :password, only: %i[edit update]
  namespace :identity do
    resource :email, only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset, only: %i[new edit create update]
  end
  post 'users/:user_id/masquerade', to: 'masquerades#create', as: :user_masquerade
  resource :invitation, only: %i[new create]
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Canchita</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body class="bg-white">
<header>
  <nav class="bg-gray-50">
    <div class="px-2 mx-auto max-w-7xl sm:px-6 lg:px-8">
      <div class="relative flex items-center justify-between h-16">
        <div
          class="flex items-center justify-center flex-1 sm:items-stretch sm:justify-start"
        >
          <div class="flex items-center flex-shrink-0">
            <img
              class="w-auto h-8"
              src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500"
              alt="Your Company"
            >
          </div>
          <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default:
            "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <a
                href="<%= url_for root_path %>"
                class="px-3 py-2 text-sm font-medium text-gray-500"
                aria-current="page"
              >Dashboard</a>
              <%= link_to "Locations",
                          locations_path,
                          class:
                            "px-3 py-2 text-sm font-medium text-gray-500"

              %>
            </div>
          </div>
        </div>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
          <div class="relative ml-3" data-controller="dropdown">
            <div>
              <button type="button" data-action="dropdown#toggleDropdown click@window->dropdown#hide" class="relative flex text-sm bg-gray-800 rounded-full focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="absolute -inset-1.5"></span>
                <span class="sr-only">Open user menu</span>
                <img class="w-8 h-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </button>
            </div>
            <div data-dropdown-target="menu" class="absolute right-0 z-10 hidden w-48 py-1 mt-2 origin-top-right bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
              <!-- Active: "bg-gray-100", Not Active: "" -->
              <!--<a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>-->
              <%= link_to "Change password", edit_password_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 w-full text-left" %>
              <%= link_to "Change email address", edit_identity_email_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 w-full text-left" %>
              <%= link_to "Send invitation", new_invitation_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 w-full text-left" %>
              <%= button_to "Signin as last user", user_masquerade_path(User.last), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 w-full text-left" %>
              <%= link_to "Devices & Sessions", sessions_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 w-full text-left" %>
              <%= button_to "Log out", Current.session, method: :delete, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 w-full text-left" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

<main class="container flex px-5 mx-auto mt-28">
  <%= yield %>
</main>

</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html class="h-full antialiased bg-white scroll-smooth">
  <head>
    <title>Canchita</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="flex flex-col h-full">
    <div class="relative flex justify-center min-h-full md:px-12 lg:px-0">
      <div class="relative z-10 flex flex-col flex-1 px-4 py-10 bg-white shadow-2xl sm:justify-center md:flex-none md:px-28">
        <main class="w-full max-w-md mx-auto sm:px-4 md:w-96 md:max-w-sm md:px-0">
          <%= yield %>
        </main>
      </div>
      <div class="hidden sm:contents lg:relative lg:block lg:flex-1"></div>
    </div>
  </body>
</html>